import {uid,EX,TREINOS,NIVEIS,FASES,FILA,localDate,addDays,num,fmt,isForca,limCardioFase} from './protocol.js';
import {clone,empty,importBackup,mergeBackup,updateSessionMeta,deleteSession,stats,week,monday,ordered,lastExecution,target,decision,progressionEvents,newDraft,reviewDraft,formatSeries,summary,name,unit} from './core.js';
import {Repository,KEYS} from './storage.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let store;try{store=window.localStorage}catch{store={getItem:()=>null,setItem:()=>{throw Error('Sem armazenamento')},removeItem:()=>{}}}
const repo=new Repository(store);let state=repo.load(),tab='hoje',draft=null,review=null,period=7,importText='',importPreview=null,importMode='merge',busy=false,lastSaved=null,notice=repo.message,updateReady=null,editingSessionId=null;
try{const r=repo.readDraft();if(r&&TREINOS[r.tipo]&&Array.isArray(r.exercicios)){draft={...newDraft(r.tipo),...r,cardio:{min:'',feito:false,zona2:false,...r.cardio}};const duplicate=state.data.sessoes.some(s=>s.data===draft.data&&s.tipo===draft.tipo);notice=duplicate?'Rascunho recuperado, mas já existe uma sessão '+draft.tipo+' nesta data. Confira o histórico antes de salvar novamente.':'Rascunho recuperado. Continue quando quiser.'}}catch{}
const data=()=>state.data,st=()=>stats(data());
function feedback(message){notice=message;$('#statusMessage').textContent=message;$('#statusMessage').hidden=!message}
function saveDraft(){try{repo.saveDraft(draft)}catch{feedback('Rascunho está só nesta tela: não foi possível gravá-lo. Exporte antes de fechar.')}}
function download(value,filename){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function persist(next,opts){state=repo.commit(next,opts);return state}
async function withBusy(button,label,task){
 if(busy)return false;
 busy=true;
 const original=button?.textContent||'';
 if(button){button.disabled=true;button.setAttribute('aria-busy','true');if(label)button.textContent=label}
 try{await task();return true}
 finally{busy=false;if(button?.isConnected){button.disabled=false;button.removeAttribute('aria-busy');if(label)button.textContent=original}}
}
function button(label,action,secondary=false,extra=''){return `<button class="btn${secondary?' sec':''}" data-action="${action}" ${extra}>${label}</button>`}
function kpi(value,label){return `<div class="kpi"><div class="n">${value}</div><div class="l">${label}</div></div>`}
function phaseInfo(){const s=st(),f=FASES[s.phase-1],previous=s.phase===1?0:s.phase===2?8:20,end=s.phase===1?8:s.phase===2?20:32;return `<div class="card"><div class="spread"><h3>Fase ${s.phase} · ${f.nome}</h3><span>${s.force}/${end} força A/B</span></div><progress max="${end-previous}" value="${Math.min(s.force-previous,end-previous)}" aria-label="Progresso da fase"></progress><small>${f.rir}. ${s.force>=32?'Bloco concluído: reavaliar antes de continuar aumentando volume.':f.o}</small></div>`}
function guardrails(){return `<details class="acc"><summary>Guardrails para o dia</summary><div class="corpo"><p><b>Descanso faz parte.</b> Siga a próxima sessão quando puder; não acrescente treino para preservar uma corrente ou compensar uma ausência.</p><p><b>Um lugar para cada informação.</b> Sono e estado emocional no Saúde; uso de Instagram, YouTube e ChatGPT no Tempo de Uso. Aqui, organize o treino.</p><p><b>Menos decisões.</b> Mantenha os limites digitais no iPhone. Use a IA para uma pergunta concreta e encerre quando a decisão estiver tomada.</p><p><b>Espaço fora da tela.</b> Preserve tempo para terapia, oração e convivência sem precisar registrar pontos ou cumprir uma lista.</p></div></details>`}
function mobGuide(){const link=state.preferences?.mobGuide;return `<div class="card"><h3>MOB · recuperar e se mover</h3><ol class="mob-steps"><li><b>Caminhada leve</b><span>Ritmo confortável, sem transformar a sessão em cardio forte.</span></li><li><b>Mobilidade ativa</b><span>Siga os movimentos da rotina já combinada.</span></li><li><b>Alongamento</b><span>Reserve espaço para a sequência habitual.</span></li><li><b>Respiração</b><span>Termine com calma.</span></li></ol><a class="btn sec" href="./guia-mob.html" target="_blank" rel="noopener">Abrir rotina MOB completa · offline</a>${link&&safeLink(link)?`<a class="btn sec" href="${esc(link)}" target="_blank" rel="noopener noreferrer">Abrir guia complementar</a>`:''}</div>`}
function safeLink(s){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)}catch{return false}}
function todayView(){const s=st(),w=week(data()),f=FASES[s.phase-1];return `<section class="hero"><div class="eyebrow">Próxima sessão da fila</div><h2>${TREINOS[s.next].nome}</h2><p class="muted">Fase ${s.phase} · ${f.rir}</p>${button(draft?'Continuar rascunho · '+draft.tipo:'Registrar '+s.next,'start')}<p class="rest-note">A fila espera por você. Descansar não apaga seu progresso.</p></section><div class="linha">${kpi(w.sessions+'<span class="muted"> / 4</span>','sessões na semana')}${kpi(w.force+'<span class="muted"> / 2</span>','força A/B na semana')}${kpi(s.force,'força A/B acumulada')}</div>${w.consistent?'<p class="okbox">Meta base da semana atendida. Não é preciso acrescentar treino.</p>':'<p class="muted">Referência semanal: 4 sessões válidas, incluindo 2 de força A/B.</p>'}${phaseInfo()}${lastSaved?`<div class="card"><h3>Sessão ${lastSaved.nivel} salva</h3>${sessionProgress(lastSaved)}${button('Ver histórico','history',true)}</div>`:''}${guardrails()}<div class="card"><h3>Apple mede. O painel organiza.</h3><p class="muted">Cargas, execução e próxima sessão aqui. Métricas fisiológicas e treinos do Watch no Apple Health.</p></div>`}
function fillPlanned(){if(!draft)draft=newDraft(st().next);const phase=st().phase;for(const e of draft.exercicios){if(!EX[e.id])continue;const visible=draft.nivel==='A'||TREINOS[draft.tipo].minimo.includes(e.id);if(!visible)continue;const n=draft.nivel==='A'?target(e.id,phase):draft.nivel==='B'?2:1;const u=lastExecution(data(),e.id);const base=u?.exercise.series.at(-1)?.kg??'';while(e.series.length<n)e.series.push({kg:base,reps:''})}}
function exerciseInput(e){const id=e.id,ex=EX[id],u=lastExecution(data(),id),sem=unit(id),n=draft.nivel==='A'?target(id,st().phase):draft.nivel==='B'?2:1;return `<section class="ex" data-ex="${id}"><div class="ex-cab"><div><h3>${name(id)}</h3><div class="ex-meta">${sem.load}</div></div><span class="tag">${n} séries</span></div><p class="ex-meta">${id==='farmer'?'20–30 passos por série · comece com 20 e evolua com a mesma carga.':ex.reps+' '+(id==='prancha'?'':'reps')+' · '+FASES[st().phase-1].rir}</p><div class="series">${e.series.map((s,i)=>`<div class="serie"><span class="series-number">${i+1}</span>${ex.semCarga?'':`<label><span>${sem.short}</span><input inputmode="decimal" data-id="${id}" data-index="${i}" data-field="kg" aria-label="${name(id)}, carga série ${i+1}, ${sem.load}" value="${esc(s.kg)}" placeholder="—"></label>`}<label><span>${sem.effort}</span><input inputmode="${id==='prancha'?'decimal':'numeric'}" data-id="${id}" data-index="${i}" data-field="reps" aria-label="${name(id)}, ${sem.effort} série ${i+1}" value="${esc(s.reps)}" placeholder="—"></label>${i>=n?`<button class="rmserie" data-action="remove-series" data-exercise="${id}" data-index="${i}" aria-label="Remover série ${i+1} de ${name(id)}">×</button>`:''}</div>`).join('')}</div><button class="addserie" data-action="add-series" data-exercise="${id}">Adicionar série</button>${u?`<div class="reference"><b>Última · ${u.session.data}</b><br>${esc(formatSeries(id,u.exercise.series))}<br><span class="${decision(u.session,id).state==='increase'?'up':''}">${esc(decision(u.session,id).reason)}</span></div>`:'<p class="muted">Sem execução anterior. Use a carga prevista no seu protocolo.</p>'}<details><summary class="small-summary">Orientação de execução</summary><p class="muted">${esc(id==='farmer'?'Postura alta e passos controlados.':id==='prancha'?'Glúteos e abdômen ativos. Registre segundos.':ex.nota)}</p></details></section>`}
function registerView(){fillPlanned();if(review)return reviewView();const force=isForca(draft.tipo),limits=limCardioFase(draft.tipo,st().phase);return `<h2>Registrar sessão</h2><div class="card"><div class="seletor cinco" aria-label="Tipo de sessão">${Object.keys(TREINOS).map(t=>`<button class="opt" data-action="type" data-value="${t}" aria-pressed="${draft.tipo===t}"><b>${t}</b><span>${t==='FA'||t==='FB'?'Força':t==='Z2'?'Zona 2':t==='MOB'?'Mobilidade':'Intervalos'}</span></button>`).join('')}</div><label class="f" for="session-date">Data</label><input class="t" type="date" id="session-date" max="${localDate()}" value="${draft.data}">${force?`<label class="f">Meta de hoje</label><div class="seletor">${Object.entries(NIVEIS).map(([k,v])=>`<button class="opt" data-action="level" data-value="${k}" aria-pressed="${draft.nivel===k}"><b>${k}</b><span>${v.n}</span></button>`).join('')}</div><small>O nível salvo será o realmente executado. Alterar a meta preserva o que você preencheu.</small>`:`<p class="muted">Classificação pelos minutos: A ≥ ${limits.A} · B ≥ ${limits.B} · C ≥ ${limits.C}. Abaixo disso: parcial.</p>`}</div>${draft.tipo==='MOB'?mobGuide():''}${force?`<div class="card">${draft.exercicios.filter(e=>draft.nivel==='A'||TREINOS[draft.tipo].minimo.includes(e.id)).map(exerciseInput).join('')}<label class="check"><input id="technique" type="checkbox" ${draft.progressaoOk?'checked':''}><span><b>Técnica e RIR confirmados.</b> A execução ficou boa e respeitei ${FASES[st().phase-1].rir}.</span></label></div>`:''}<div class="card"><h3>${force?'Cardio após a força (opcional)':draft.tipo==='MOB'?'Duração total da sessão':'Duração'}</h3>${force?`<label class="check"><input id="cardio-done" type="checkbox" ${draft.cardio.feito?'checked':''}>Fiz cardio</label>`:''}<label class="f" for="minutes">Minutos${force?' (opcional)':''}</label><input class="t" inputmode="decimal" id="minutes" value="${esc(draft.cardio.min)}">${draft.tipo==='Z2'?`<label class="check"><input id="zone2" type="checkbox" ${draft.cardio.zona2?'checked':''}><span>Confirmei Zona 2 pelo Watch / teste da fala.</span></label>`:''}${force?'<small>A duração, se preenchida, também indica cardio feito.</small>':'<small>FC, distância e demais métricas ficam no Apple Health.</small>'}</div><div class="card"><label class="f" for="notes">Nota opcional</label><textarea class="t" id="notes" placeholder="Algum ajuste ou observação sobre esta sessão">${esc(draft.notas)}</textarea></div>${button('Revisar sessão','review')}<div class="btnrow">${button('Exportar rascunho','draft-export',true)}${button('Descartar rascunho','discard',true)}</div>`}
function sessionProgress(s){if(!isForca(s.tipo))return '<p class="muted">'+(s.nivel==='P'?'Registro parcial: não avança a fila.':'A fila só avança se o tipo era o próximo esperado.')+'</p>';const groups={increase:[],maintain:[],reps:[]};for(const e of s.exercicios){const d=decision(s,e.id);groups[d.state].push(`<li><b>${esc(name(e.id))}</b><br>${esc(d.reason)}</li>`)}return Object.entries({increase:'Podem subir no próximo A',maintain:'Manter',reps:'Progredindo em repetições / tempo / passos'}).filter(([k])=>groups[k].length).map(([k,v])=>`<div class="progress-group ${k}"><h4>${v}</h4><ul>${groups[k].join('')}</ul></div>`).join('')}
function reviewView(){const s=review.session;return `<h2 tabindex="-1" id="review-title">Revise antes de salvar</h2><div class="card"><div class="spread"><h3>${s.tipo} · ${s.data}</h3><span class="tag f">Meta ${s.meta} → ${s.nivel}</span></div><p>Fase ${s.fase} · ${s.nivel==='P'?'parcial':NIVEIS[s.nivel].n}</p></div>${review.warnings.length?`<div class="aviso" role="alert"><b>Confira estes pontos</b><ul>${review.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></div>`:''}<div class="card">${s.exercicios.map(e=>`<div class="review-ex"><h3>${esc(name(e.id))}</h3><small>${unit(e.id).load}</small><p>${esc(formatSeries(e.id,e.series))}</p>${lastExecution(data(),e.id)?`<p class="reference">Anterior · ${lastExecution(data(),e.id).session.data}<br>${esc(formatSeries(e.id,lastExecution(data(),e.id).exercise.series))}</p>`:''}</div>`).join('')||'<p>Sem séries de força registradas.</p>'}<p><b>Cardio:</b> ${s.cardio.feito?'feito · ':''}${s.cardio.min??'duração não informada'}${s.cardio.min!==undefined?' min':''}</p>${s.tipo==='Z2'?`<p>Zona 2: ${s.cardio.zona2Confirmada?'confirmada':'não confirmada'}</p>`:''}<p><b>Técnica e RIR:</b> ${(s.techniqueRirConfirmed??s.progressaoOk)?'confirmados':'não confirmados'}${!s.progressaoOk?' · sem autorização de progressão':''}</p>${s.notas?`<p><b>Nota:</b> ${esc(s.notas)}</p>`:''}</div><div class="card"><h3>Próxima execução</h3>${sessionProgress(s)}</div>${review.warnings.length?'<label class="check"><input type="checkbox" id="review-ack"><span>Revisei os avisos e confirmo que esta é a execução real.</span></label>':''}${!repo.canWrite?'<div class="aviso" role="alert">A gravação local está indisponível. Você ainda pode voltar e exportar o rascunho em Dados.</div>':''}<div class="btnrow">${button('Voltar e corrigir','back-review',true)}${button('Confirmar e salvar','confirm-save')}</div>`}
function historyView(){const ds=data(),s=st(),weeks=[];for(let i=7;i>=0;i--){const date=addDays(monday(localDate()),-7*i);if(!ds.sessoes.some(s=>s.data<=addDays(date,6)))continue;weeks.push({date,...week(ds,date)})}const consistent=weeks.filter(w=>w.consistent).length;return `<h2>Progresso e histórico</h2><div class="linha">${kpi(s.valid,'sessões válidas')}${kpi(s.force,'força A/B')}${kpi(consistent,'semanas consistentes nas últimas 8')}</div>${phaseInfo()}<div class="card"><h3>Semanas · referência de 4 sessões</h3><div class="week-chart">${weeks.map(w=>`<div class="week-bar"><span>${w.sessions}</span><div style="height:${Math.max(2,Math.min(w.sessions,12)*9)}px" class="bar ${w.consistent?'consistent':''}"></div><small>${w.date.slice(8)}/${w.date.slice(5,7)}</small></div>`).join('')}</div><p class="muted">Semana consistente: ≥ 4 sessões válidas, com ≥ 2 de força A/B. Semanas sem sessão continuam visíveis.</p></div><div class="card"><h3>Últimas execuções</h3><p class="muted">Cargas na unidade de cada exercício. Placas não são kg.</p>${Object.keys(EX).map(id=>{const u=lastExecution(ds,id);return u?`<details class="acc"><summary>${name(id)}</summary><div class="corpo"><p>${u.session.data} · ${unit(id).load}</p><p>${esc(formatSeries(id,u.exercise.series))}</p><p>${esc(decision(u.session,id).reason)}</p>${ordered(ds).filter(s=>s.exercicios.some(e=>e.id===id)).map(s=>`<p class="history-line">${s.data} · ${esc(formatSeries(id,s.exercicios.find(e=>e.id===id).series))}</p>`).join('')}</div></details>`:''}).join('')||'<p>A primeira execução aparecerá aqui.</p>'}</div><h2>Todas as sessões · ${s.total}</h2>${ordered(ds).reverse().map(sessionCard).join('')||'<p class="vazio">Ainda não há sessões.</p>'}`}
function sessionCard(s){
 if(editingSessionId===s.id)return `<div class="card" data-edit-session="${esc(s.id)}"><div class="spread"><h3>Corrigir registro · ${s.tipo}</h3><span class="tag">${s.nivel==='P'?'parcial':s.nivel}</span></div><p class="muted">A correção preserva ID, execução, cargas, séries e horário original. Para alterar o conteúdo do treino, exclua a sessão e registre novamente.</p><label class="f" for="edit-session-date">Data</label><input class="t" type="date" id="edit-session-date" max="${localDate()}" value="${esc(s.data)}"><label class="f" for="edit-session-notes">Nota</label><textarea class="t" id="edit-session-notes">${esc(s.notas||'')}</textarea><div class="btnrow">${button('Cancelar','cancel-session-edit',true,`data-id="${esc(s.id)}"`)}${button('Salvar correção','save-session-edit',false,`data-id="${esc(s.id)}"`)}</div></div>`;
 return `<details class="acc"><summary>${esc(s.data)} · ${s.tipo} · ${s.nivel==='P'?'parcial':s.nivel}</summary><div class="corpo"><p>Meta ${s.meta} · fase ${s.fase} · técnica/RIR ${(s.techniqueRirConfirmed??s.progressaoOk)?'confirmados':'não confirmados'}</p>${s.exercicios.map(e=>`<p><b>${esc(name(e.id))}</b><br>${esc(formatSeries(e.id,e.series))}</p>`).join('')}<p>Cardio: ${esc(s.cardio.min??'—')} min${s.cardio.feito?' · feito':''}</p>${s.cardio.zona2Confirmada!==undefined?`<p>Zona 2 ${s.cardio.zona2Confirmada?'confirmada':'não confirmada'}</p>`:''}${s.notas?`<p class="note">${esc(s.notas)}</p>`:''}<div class="btnrow record-actions">${button('Corrigir data / nota','edit-session',true,`data-id="${esc(s.id)}"`)}${button('Excluir sessão','delete-session',true,`data-id="${esc(s.id)}"`)}</div><details><summary class="small-summary">Registro original completo</summary><pre>${esc(JSON.stringify(s,null,2))}</pre></details></div></details>`;
}
function planView(){return `<h2>Seu protocolo</h2>${phaseInfo()}<div class="card"><h3>Fila de 8 sessões</h3><div class="queue">${FILA.map((t,i)=>`<span class="tag ${i===st().position%8?'f':''}">${i+1}. ${t}${i===st().position%8?' · próxima':''}</span>`).join('')}</div><p class="muted">Extras ficam no histórico; só a sessão esperada avança a fila. Antes de 4 treinos de força A/B, o slot INT vira Z2.</p></div>${FASES.map(f=>`<details class="acc"><summary>Fase ${f.n} · ${f.nome}</summary><div class="corpo"><p>${f.faixa} · ${f.rir}</p><ul>${f.d.map(s=>`<li>${s}</li>`).join('')}</ul></div></details>`).join('')}<div class="card"><h3>Progressão de carga</h3><p>Apenas execução com meta A e nível real A, séries planejadas no topo da faixa, carga uniforme e técnica/RIR confirmados autoriza aumento no próximo A.</p><p class="muted">B/C e parcial não autorizam. Depois do aumento, volte perto do piso da faixa.</p></div>${['FA','FB'].map(t=>`<details class="acc"><summary>${TREINOS[t].nome}</summary><div class="corpo">${TREINOS[t].ex.map(id=>`<p><b>${name(id)}</b><br>${EX[id].s.join(' / ')} séries nas fases 1/2/3 · ${id==='farmer'?'20–30 passos · comece com 20; todas as séries em 30 permitem avaliar aumento no próximo A':EX[id].reps}<br><small>${unit(id).load}</small></p>`).join('')}<p>B: ${TREINOS[t].minimo.map(name).join(', ')} × 2 séries. C: os mesmos × 1.</p></div></details>`).join('')}${mobGuide()}${guardrails()}`}
function dataView(){return `<h2>Dados e backup</h2>
<div class="card"><h3>Resumo para IA</h3><label class="f" for="period">Período</label><select class="t" id="period">${[[7,'7 dias'],[14,'14 dias'],[30,'30 dias'],['all','Histórico completo']].map(([v,l])=>`<option value="${v}" ${String(period)===String(v)?'selected':''}>${l}</option>`).join('')}</select><div class="btnrow">${button('Copiar resumo','copy-summary')}${button('Ver resumo','show-summary',true)}</div><textarea id="summary-text" class="t" readonly hidden aria-label="Resumo para IA"></textarea></div>
<div class="card"><h3>Backup</h3><p class="muted">O backup usa um formato estável do Painel de Saúde, independente da versão do aplicativo. Mantenha uma cópia fora do navegador.</p><div class="btnrow">${button('Exportar JSON','export')}${button('Copiar backup','copy-backup',true)}</div><details class="acc"><summary>Importar ou mesclar backup</summary><div class="corpo"><label class="f" for="backup-file">Arquivo JSON</label><input class="t" type="file" id="backup-file" accept=".json,application/json"><label class="f" for="backup-text">Ou cole o JSON</label><textarea class="t" id="backup-text">${esc(importText)}</textarea><label class="f" for="import-mode">Como importar</label><select class="t" id="import-mode"><option value="merge" ${importMode==='merge'?'selected':''}>Mesclar por ID (sem sobrescrever conflitos)</option><option value="replace" ${importMode==='replace'?'selected':''}>Substituir, guardando cópia de segurança</option></select>${button('Conferir importação','preview-import')}${importPreview?`<div class="okbox"><p>Backup reconhecido. Resultado: ${stats(importPreview.next.data).total} sessões · ${stats(importPreview.next.data).force} força A/B · fase ${stats(importPreview.next.data).phase} · próxima ${stats(importPreview.next.data).next}.</p><p>${importMode==='merge'?importPreview.added+' sessões/medidas novas.':'O estado atual será guardado para recuperação.'}</p>${button('Confirmar importação','confirm-import')}</div>`:''}</div></details></div>
<div class="card"><h3>Recuperação</h3><p class="muted">Antes de substituir ou restaurar dados, exporte um backup atual.</p><div class="btnrow">${button('Exportar cópia anterior','export-rollback',true)}${button('Restaurar cópia anterior','restore',true)}</div>${button('Exportar armazenamento bruto','raw-export',true)}${draft?button('Exportar rascunho','draft-export',true):''}<label class="f" for="draft-file">Recuperar rascunho exportado</label><input class="t" type="file" id="draft-file" accept=".json,application/json"></div>
<div class="card"><h3>Guia ilustrado de MOB</h3><p class="muted">A rotina completa está em Plano e no registro MOB, com imagens e texto disponíveis offline. Aqui você pode guardar um link complementar.</p><label class="f" for="mob-link">Link complementar (opcional)</label><input class="t" type="url" id="mob-link" value="${esc(state.preferences?.mobGuide||'')}" placeholder="https://…">${button('Salvar link','save-guide',true)}</div>
<div class="card"><h3>Apple Health</h3><p>Fonte de sono, HRV, FC, VO₂ máx, recuperação cardíaca, respiração, passos, distância, energia, minutos de exercício, workouts, peso, cintura e State of Mind.</p><p class="muted">Health Auto Export é a ponte para análise junto do resumo do painel. Não importe seu JSON de Health aqui.</p>${data().medidas.length?`<details><summary>Medidas históricas preservadas · ${data().medidas.length}</summary><pre>${esc(JSON.stringify(data().medidas,null,2))}</pre></details>`:''}</div>`}
function render(){const views={hoje:todayView,registrar:registerView,progresso:historyView,plano:planView,dados:dataView};$('#app').innerHTML=views[tab]();$('#storageStatus').textContent=repo.canWrite?'Dados locais · '+(navigator.onLine?'online':'offline'):'Gravação bloqueada · consulte Dados';$('#storageStatus').className='storage '+(repo.canWrite?'ok':'bad');$('#date-label').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));feedback(notice);$('#update-banner').hidden=!updateReady;if(importPreview&&tab==='dados')$('#backup-file')?.closest('details')?.setAttribute('open','');}
function navigate(next){tab=next;review=null;notice='';render();window.scrollTo(0,0);$('#page-heading')?.focus()}
function wantChange(){return draft&&(draft.notas?.trim()||draft.progressaoOk||num(draft.cardio.min)>0||draft.cardio.feito||draft.exercicios.some(e=>e.series.some(s=>num(s.reps)>0)))}
async function copy(text){try{await navigator.clipboard.writeText(text);feedback('Copiado.')}catch{const a=document.createElement('textarea');a.className='t';a.value=text;$('#app').append(a);a.focus();a.select();feedback('Selecione o texto exibido e copie manualmente.')}}
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.tab){navigate(b.dataset.tab);return}const action=b.dataset.action;if(!action||busy)return;
 try{
  if(action==='start'){if(!draft)draft=newDraft(st().next);navigate('registrar')}
  if(action==='history')navigate('progresso');
  if(action==='type'){if(draft.tipo!==b.dataset.value){if(wantChange()&&!confirm('Trocar o tipo descarta este rascunho. Deseja trocar?'))return;draft=newDraft(b.dataset.value);saveDraft();render()}}
  if(action==='level'){draft.nivel=b.dataset.value;saveDraft();render()}
  if(action==='add-series'){const e=draft.exercicios.find(x=>x.id===b.dataset.exercise);e.series.push({kg:e.series.at(-1)?.kg??'',reps:''});saveDraft();render()}
  if(action==='remove-series'){draft.exercicios.find(x=>x.id===b.dataset.exercise).series.splice(Number(b.dataset.index),1);saveDraft();render()}
  if(action==='review'){const r=reviewDraft(draft,data());if(r.errors.length){feedback(r.errors.join(' '));$('#statusMessage').scrollIntoView({block:'center'});return}review=r;render();window.scrollTo(0,0);$('#review-title').focus()}
  if(action==='back-review'){review=null;render()}
  if(action==='confirm-save'){
   if(!review)return;if(!repo.canWrite){feedback('Gravação local indisponível. Volte, exporte o rascunho e reabra o painel antes de tentar salvar.');return}if(review.warnings.length&&!$('#review-ack')?.checked){feedback('Confirme os avisos ou volte para corrigir.');return}
   await withBusy(b,'Salvando…',async()=>{
    feedback('Salvando sessão…');
    const next=clone(state),session={...review.session,id:uid('s'),criadoEm:new Date().toISOString()};
    next.data.sessoes.push(session);next.data.atualizado=session.criadoEm;next.lastSavedAt=session.criadoEm;
    await persist(next);lastSaved=session;draft=null;review=null;
    try{repo.clearDraft()}catch{feedback('Sessão salva, mas não foi possível limpar o rascunho armazenado.')}
    navigate('hoje');feedback('Sessão '+session.nivel+' salva.');
   });
   return;
  }
  if(action==='edit-session'){editingSessionId=b.dataset.id;render();document.querySelector(`[data-edit-session="${CSS.escape(editingSessionId)}"]`)?.scrollIntoView({block:'center'});return}
  if(action==='cancel-session-edit'){editingSessionId=null;render();return}
  if(action==='save-session-edit'){
   const id=b.dataset.id,original=data().sessoes.find(s=>s.id===id);if(!original)throw Error('Sessão não encontrada.');
   const sessionDate=$('#edit-session-date')?.value||'',notes=$('#edit-session-notes')?.value||'';
   const duplicate=data().sessoes.some(s=>s.id!==id&&s.data===sessionDate&&s.tipo===original.tipo);
   if(duplicate&&!confirm(`Já existe ${original.tipo} em ${sessionDate}. Salvar mesmo assim?`))return;
   await withBusy(b,'Salvando…',async()=>{const next=clone(state),now=new Date().toISOString();next.data=updateSessionMeta(next.data,id,{data:sessionDate,notas:notes},localDate());next.data.atualizado=now;next.lastSavedAt=now;await persist(next,{checkpoint:true});editingSessionId=null;lastSaved=null;render();feedback('Registro corrigido. A cópia anterior ficou disponível em Dados → Recuperação.');});return
  }
  if(action==='delete-session'){
   const id=b.dataset.id,original=data().sessoes.find(s=>s.id===id);if(!original)throw Error('Sessão não encontrada.');
   if(!confirm(`Excluir ${original.tipo} de ${original.data}? Esta ação altera histórico, fila e indicadores. Uma cópia anterior será criada automaticamente.`))return;
   await withBusy(b,'Excluindo…',async()=>{const next=clone(state),now=new Date().toISOString();next.data=deleteSession(next.data,id);next.data.atualizado=now;next.lastSavedAt=now;await persist(next,{checkpoint:true});editingSessionId=null;lastSaved=null;render();feedback('Sessão excluída. A cópia anterior ficou disponível em Dados → Recuperação.');});return
  }
  if(action==='discard'){if(confirm('Descartar somente este rascunho?')){draft=null;repo.clearDraft();navigate('hoje')}}
  if(action==='draft-export')download({schema:'painel-saude/draft',format:1,rascunho:draft},'painel-saude-rascunho-'+localDate()+'.json');
  if(action==='export')download(state,'painel-saude-backup-'+localDate()+'.json');
  if(action==='copy-backup')await copy(JSON.stringify(state));
  if(action==='copy-summary')await copy(summary(data(),period));
  if(action==='show-summary'){const a=$('#summary-text');a.hidden=false;a.value=summary(data(),period)}
  if(action==='preview-import'){
   const raw=importBackup(JSON.parse(importText));const result=importMode==='merge'?mergeBackup(state,raw):{state:raw,added:0};importPreview={next:result.state,added:result.added};render();
  }
  if(action==='confirm-import'&&importPreview){await withBusy(b,'Importando…',async()=>{await persist(importPreview.next,{checkpoint:true,recover:!repo.canWrite});importPreview=null;importText='';lastSaved=null;render();feedback('Importação concluída: '+st().total+' sessões. Histórico preservado.');});return}
  if(action==='export-rollback'){const raw=store.getItem(KEYS.rollback)||store.getItem(KEYS.bak);if(!raw)throw Error('Ainda não há cópia anterior.');download(raw,'painel-saude-copia-anterior.json')}
  if(action==='restore'){const raw=store.getItem(KEYS.rollback)||store.getItem(KEYS.bak);if(!raw)throw Error('Ainda não há cópia anterior.');const candidate=importBackup(JSON.parse(raw));if(confirm('Restaurar '+stats(candidate.data).total+' sessões? Exporte o estado atual antes.')){await withBusy(b,'Restaurando…',async()=>{await persist(candidate,{checkpoint:true,recover:!repo.canWrite});navigate('dados');feedback('Cópia anterior restaurada.');});}return}
  if(action==='raw-export')download(Object.fromEntries(Object.entries(KEYS).map(([label,key])=>[label,store.getItem(key)])),'painel-saude-armazenamento-bruto.json');
  if(action==='save-guide'){const link=$('#mob-link').value.trim();if(link&&!safeLink(link))throw Error('Use um link http ou https válido.');const next=clone(state);next.preferences={...next.preferences,mobGuide:link};await withBusy(b,'Salvando…',async()=>{await persist(next);feedback('Link do guia salvo.');});return}
  if(action==='update'){saveDraft();updateReady.postMessage({type:'SKIP_WAITING'});feedback('Atualizando o aplicativo…')}
 }catch(e){feedback(e.message||'Não foi possível concluir a ação. Seus registros foram mantidos.')}
});
document.addEventListener('input',e=>{const t=e.target;
 if(t.id==='backup-text'){importText=t.value;importPreview=null;return}
 if(!draft||tab!=='registrar'||review)return;
 if(t.dataset.field){draft.exercicios.find(x=>x.id===t.dataset.id).series[+t.dataset.index][t.dataset.field]=t.value.replace(',','.');}
 if(t.id==='session-date')draft.data=t.value;
 if(t.id==='notes')draft.notas=t.value;
 if(t.id==='minutes')draft.cardio.min=t.value.replace(',','.');
 if(t.id==='technique')draft.progressaoOk=t.checked;
 if(t.id==='cardio-done')draft.cardio.feito=t.checked;
 if(t.id==='zone2')draft.cardio.zona2=t.checked;
 saveDraft();
});
document.addEventListener('change',async e=>{const t=e.target;try{
 if(t.id==='period'){period=t.value;const a=$('#summary-text');if(a&&!a.hidden)a.value=summary(data(),period)}
 if(t.id==='import-mode'){importMode=t.value;importPreview=null;render();$('#backup-text')?.closest('details')?.setAttribute('open','')}
 if(t.id==='backup-file'&&t.files[0]){importText=await t.files[0].text();importPreview=null;$('#backup-text').value=importText;feedback('Arquivo lido. Toque em Conferir importação.');}
 if(t.id==='draft-file'&&t.files[0]){const raw=JSON.parse(await t.files[0].text());if(!raw?.rascunho||!TREINOS[raw.rascunho.tipo])throw Error('Arquivo de rascunho inválido.');const d=raw.rascunho;reviewDraft(d,data());if(wantChange()&&!confirm('Substituir o rascunho atual pelo arquivo?'))return;draft=d;saveDraft();navigate('registrar');feedback('Rascunho recuperado.');}
 }catch(err){feedback(err.message)}});
window.addEventListener('storage',e=>{if(e.key===KEYS.main){repo.canWrite=false;feedback('Histórico alterado em outra janela. Exporte o rascunho e reabra antes de salvar.')}});
window.addEventListener('pagehide',()=>{if(draft)saveDraft()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&draft)saveDraft()});
window.addEventListener('online',render);window.addEventListener('offline',render);
render();
if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost')){
 navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'}).then(reg=>{
  const pending=()=>{if(reg.waiting){updateReady=reg.waiting;$('#update-banner').hidden=false}};pending();reg.addEventListener('updatefound',()=>{reg.installing?.addEventListener('statechange',pending)});reg.update().catch(()=>{});
 }).catch(()=>feedback('Uso offline ainda não disponível. Abra o painel online novamente.'));
 let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!refreshing&&updateReady){refreshing=true;location.reload()}});
}
